### ISSUE TITLE
AGRC Geocoding Toolbox

### ISSUE THREAD

**Issue by ebrutsch** [agrc/agrc.github.io#162]
## Issue description
I used to be able to use the geocoding toolbox without any issues. Several months ago I started having problems where it would code part of a table and then give up. I could work around it by breaking the table into smaller ones after the point where it would hit an error (I wasn't doing a ton of locations, ~400 in the original table). Now it fails without accomplishing anything. I don't know if I'm doing something wrong on my end, and I don't know enough Python to be able to effectively troubleshoot this myself.
Here is the table I'm currently working with (125 locations):

[Naloxone finished with zip code sheet.xlsx](https://github.com/agrc/agrc.github.io/files/318908/Naloxone.finished.with.zip.code.sheet.xlsx)

#### Expected result
I expected: "Yay! Here are the locations! Now you can display them in a map!"

#### Actual result
Instead:

Executing: GeocodeTable AGRC-61FFB138304379 Sheet1$ OBJ_ID StreetAddress Zip "Address points and road centerlines (default)" "NAD 1983 UTM Zone 12N" C:\Users\ebrutsch\Desktop\Geocoding
Start Time: Thu Jun 16 09:39:35 2016
Running script GeocodeTable...
Geocode Table Version 2.1.7
Api key is valid.
Begin Geocode.
Failed script GeocodeTable...

Traceback (most recent call last):
  File "c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\AGRC Geocode Tools.tbx#GeocodeTable.py", line 330, in <module>
  File "c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\AGRC Geocode Tools.tbx#GeocodeTable.py", line 304, in start
  File "c:\program files (x86)\arcgis\desktop10.3\ArcToolbox\Toolboxes\AGRC Geocode Tools.tbx#GeocodeTable.py", line 67, in locateAddresses
UnboundLocalError: local variable 'r' referenced before assignment

Failed to execute (GeocodeTable).
Failed at Thu Jun 16 09:39:58 2016 (Elapsed Time: 23.16 seconds)

**Comment by steveoh** [comment]
I am moving [this to here](https://github.com/agrc/geocoding-addin/issues/9). @keatonwalker should be able to help you through this. I did notice there is a `2.1.9` version and you are on `2.1.7`. I would try upgrading and see if the problem continues. Let's continue this issue in the correct repo. Thank you for submitting it.
