### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by steveoh** [agrc/agrc.github.io#62]
https://github.com/isaacs/github/issues/156

GitHub Pages does not support SSL for custom domains. We may have to move away from github pages if they will not create a way for people to use their own certs.

**Comment by steveoh** [comment]
I was just turned on to a way we can offer https for gis.utah.gov. Netlify has an open source account that listens to commits to github and publishes to http://general-manager-ant-30663.netlify.com. They have lets-encrypt support. I think all that we need to do is update our domain to point to this url and we'd be good to go. @BGranberg would you be interested in pulling the trigger on this?

**Comment by jdalton** [comment]
Just popping in to 👍 Netlify!

You can rename the account reference for example:
https://lodash.netlify.com/
https://master--lodash.netlify.com/

For my custom-domain, https://lodash.com/,  I pointed "https://lodash.netlify.com/"

**Comment by steveoh** [comment]
@jdalton did you create the lets-encrypt cert after pointing the domain to netlify?

**Comment by jdalton** [comment]
Yes, after. It will warn you to ensure the domain is working without HTTPS first. I had HSTS enabled previously so used IE9 (which doesn't support it) to confirm the site was reachable without HTTPS and then just clicked it on it and ✨ instant TLS/SSL.

**Comment by jdalton** [comment]
More info on setting up the custom domain:
https://www.netlify.com/docs/custom-domains

**Comment by steveoh** [comment]
@brigsz will you schedule a CNAME change for our website?

**Comment by jdalton** [comment]
For reference my settings are:
<img width="100%" src="https://cloud.githubusercontent.com/assets/4303/18188255/a1d6750e-7065-11e6-927b-4f4a1f51c254.png">

**Comment by brigsz** [comment]
@steveoh If I understand you want me to do an actual change request to change the CNAME from whatever it is now...agrc.github.io to gis-utah-gov.netlify.com  Is that correct?

**Comment by steveoh** [comment]
INC0548516

**Comment by steveoh** [comment]
🔓 👉 🔒
