### ISSUE TITLE
agrc.github.io/templater is getting rewritten to gis.utah.gov/templater

### ISSUE THREAD

**Issue by stdavis** [agrc/agrc.github.io#63]
Not sure if this was intended or not.

Test:  http://agrc.github.io/templater

**Comment by steveoh** [comment]
I think all of our gh-pages will do that from now on.

**Comment by stdavis** [comment]
OK. No problem. Just wanted you to be aware. I guess we'll just need to be careful of naming conflicts. No agrc/developer or agrc/data repos that use gh-pages.

**Comment by steveoh** [comment]
yeah I wondered about that myself.
